### ISSUE TITLE
Unable to find ubuntu/vivid64

### ISSUE THREAD

**Issue by farorm** [Brandon-Godwin/vagrant-kerberos-environment#1]
First great work providing this vagrant file, it was just what I was looking for. But when i clone the repo and do vagrant up I get the following error message:

"The box 'ubuntu/vivid64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/vivid64"]
Error: The requested URL returned error: 404 Not Found"

Whats the simplest way of fixing it?

**Comment by brandongodwin** [comment]
I ran into this problem on a fresh installation of Windows 10. If you run `C:\HashiCorp\Vagrant\embedded\bin/curl.EXE http://google.com`, does it complain about not being able to start `curl.exe`?

If so, you might need to install the [Microsoft Visual C++ 2010 Redistributable x86](http://www.microsoft.com/en-us/download/details.aspx?id=8328)

[Here's some more info about this problem.](https://github.com/mitchellh/vagrant/issues/6754)

**Comment by farorm** [comment]
Thanks for taking some time to answer. I just switched image to dc.vm.box = "larryli/vivid64" instead and it worked.

**Comment by brandongodwin** [comment]
Looks like they pulled the Vivid boxes when they went End of Life. That's what I get for not using a LTS release. I switched the box to Trusty and everything seems to be working. I don't remember why I used Vivid in the first place.

Thanks for bringing this to my attention.
