### ISSUE TITLE
License of this project

### ISSUE THREAD

**Issue by floragunn** [Brandon-Godwin/vagrant-kerberos-environment#2]
What is the license of this project? Currently no LICENSE file exists and so i assume its "github default license" which effectively means "All rights reserved". We would like to use code from this project but we can only do that if the project would be licensed under a open source license like Apache2, MIT, ... Would that be possible?

**Comment by brandongodwin** [comment]
Yea, I put it under the MIT license.

**Comment by floragunn** [comment]
great, thx
